version: '3.7'
services:
  ala-php:
    build:
      context: ./
      dockerfile: ./ops/docker/prod/php-fpm/Dockerfile
    container_name: ala-php
    ports:
      - "9000:80"
      - "9001:443"
    depends_on:
      - ala-mysql
    volumes:
      - ./:/app
    tty: true

  ala-mysql:
    image: mysql:8.0
    container_name: ala-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ala
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./ops/mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
